{
  "uid" : "c9539751c3c5df24",
  "name" : "test_edit_settings_process",
  "fullName" : "docs.testcases.test_all_in_one.TestConduit#test_edit_settings_process",
  "historyId" : "5db536b666a5301d0305b17b61ccff8c",
  "time" : {
    "start" : 1628142016533,
    "stop" : 1628142026931,
    "duration" : 10398
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'edit_user.csv'",
  "statusTrace" : "self = <test_all_in_one.TestConduit object at 0x7f425d108d60>\n\n    def test_edit_settings_process(self):\n        basic_login(self.driver)\n    \n        self.driver.find_element_by_xpath(\"//a[@href='#/settings']\").click()\n    \n        time.sleep(2)\n    \n        # Your Settings oldal megjelenésének ellenőrzése\n        settings_check = self.driver.find_element_by_tag_name(\"h1\").text\n        assert settings_check == \"Your Settings\", f\"Test Failed: Page names did not match expected ({settings_check}).\"\n    \n        time.sleep(3)\n    \n        # Beolvassuk az előkészített adatokat\n>       with open('edit_user.csv') as article_file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'edit_user.csv'\n\ndocs/testcases/test_all_in_one.py:149: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'edit_user.csv'",
    "statusTrace" : "self = <test_all_in_one.TestConduit object at 0x7f425d108d60>\n\n    def test_edit_settings_process(self):\n        basic_login(self.driver)\n    \n        self.driver.find_element_by_xpath(\"//a[@href='#/settings']\").click()\n    \n        time.sleep(2)\n    \n        # Your Settings oldal megjelenésének ellenőrzése\n        settings_check = self.driver.find_element_by_tag_name(\"h1\").text\n        assert settings_check == \"Your Settings\", f\"Test Failed: Page names did not match expected ({settings_check}).\"\n    \n        time.sleep(3)\n    \n        # Beolvassuk az előkészített adatokat\n>       with open('edit_user.csv') as article_file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'edit_user.csv'\n\ndocs/testcases/test_all_in_one.py:149: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "39ee22d6a26cd5e0",
      "name" : "log",
      "source" : "39ee22d6a26cd5e0.txt",
      "type" : "text/plain",
      "size" : 344
    }, {
      "uid" : "cbcbac4c2f609f45",
      "name" : "stderr",
      "source" : "cbcbac4c2f609f45.txt",
      "type" : "text/plain",
      "size" : 215
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "docs.testcases"
  }, {
    "name" : "suite",
    "value" : "test_all_in_one"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az28-873"
  }, {
    "name" : "thread",
    "value" : "3872-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "docs.testcases.test_all_in_one"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "c9539751c3c5df24.json",
  "parameterValues" : [ ]
}